"""Ingest-time scalar defaults for labels absent from V4.113 workbook (M2.4)."""

from __future__ import annotations

INGEST_SCALAR_DEFAULTS: dict[str, float] = {
    'AI Stack R&D — CAGR (taper)': -0.1,
    'AI Stack R&D — end-state % (floor)': 0.05,
    'AI Stack R&D — start % of AI Stack rev': 0.15,
    'AI: ODC first compute-sat build year': 2028.0,
    'Allocation sharpness β (top-level 3-module blend)': 3.0,
    'Allocator min softmax share floor per module (frac)': 0.05,
    'BB-share of ODC bandwidth claim': 0.5,
    'Base turnaround time per booster (years/flight)': 1.0,
    'Cadence ceiling (flights/booster/year)': 24.0,
    'CapEx slug per MW ($mm)': 20.0,
    'Capital lifetime: BV straight-line depreciation (years)': 10.0,
    'Chip cost ASP ($/chip): derived': 0.0,
    'Chip cost-per-TFLOPS decline rate g (per-FLOP, A8.2)': 0.15,
    'Chips per sat': 0.0,
    'Compute power per sat (kW)': 140.0,
    'Credence on Model A (Pr(A))': 0.6,
    'Customer Launch R&D: CAGR (taper)': -0.2,
    'Customer Launch R&D: end-state % (floor)': 0.04,
    'Customer Launch R&D: start % of external rev': 0.25,
    'Customer Launch depreciation useful life (years)': 5.0,
    'Customer Launch ground equipment CapEx % of revenue': 0.005,
    'Customer Launch ground ops % of revenue': 0.01,
    'Customer Launch maintenance CapEx % of module CapEx': 0.0,
    'Customer Service — flat % of Starlink subscription rev': 0.02,
    'DTC ARPU ($/sub/mo): year-row': 16.0,
    'Effective Compute Ratio (ECR)': 0.6,
    'Effective Compute Ratio (ratio)': 0.6,
    'Engine facility base capacity 2025 (engines/yr)': 0.0,
    'Engine facility capacity (engines/yr per increment)': 1.0,
    'Engine facility cost per capacity increment ($mm)': 0.0,
    'Engine facility useful life (years)': 25.0,
    'F9 booster accounting depreciation cap (flights)': 25.0,
    'F9 retirement rate (% of launches/year)': 0.01,
    'FCF repayment sweep (% of excess FCF)': 0.5,
    'First mission year (Lunar Mars)': 2028.0,
    'GNI per capita growth rate (annual)': 0.03,
    'Gbps per GWh/yr of ODC compute energy': 0.05,
    'General & Administrative — CAGR (taper)': 0.01,
    'General & Administrative — end-state % (ceiling)': 0.06,
    'General & Administrative: start % of group rev': 0.05,
    'Gigabay base capacity 2025 (ships/yr)': 8.0,
    'Ground station build CapEx per station ($mm)': 0.0,
    'Ground station useful life (years)': 15.0,
    'Ground stations built per year (placeholder, flat)': 0.0,
    'Group WACC': 0.1,
    'HQ facility CapEx (% of revenue)': 0.0,
    'HQ facility useful life (years)': 30.0,
    'Labour unit base hourly output ($/hr; burdened $22/0.7)': 31.43,
    'Labour unit daily working hours': 22.0,
    'Labour unit mass (kg)': 60.0,
    'Labour unit productivity factor vs human baseline': 1.0,
    'Labour unit productivity learning rate (%/yr)': 0.05,
    'Launch insurance % of external revenue': 0.05,
    'Launch other COGS % of external revenue': 0.02,
    'Launch pad build/upgrade cost ($mm per pad)': 0.0,
    'Launch pad useful life (years)': 30.0,
    'Launch pads base in service 2025 (Starship-capable)': 0.0,
    'Launches per Starship vehicle per year (cadence × variant blend, used for sizing)': 24.0,
    'Legacy V1/V1.5 Bandwidth — end-2025 (Gbps)': 71888.0,
    'Legacy V1/V1.5 D&A baseline ($mm, 2025 anchor)': 130.0,
    'Legacy V1/V1.5 D&A useful life (yrs)': 4.0,
    'Lifetime reuses per ship (cap)': 30.0,
    'Lunar fuel depot multiplier per outbound Starship': 1.0,
    'Lunar payload per surface-landed Starship (kg)': 50000.0,
    'Lunar/Mars carve-out % of prior-year Group FCF': 0.15,
    'Lunar/Mars carve-out floor ($mm/yr)': 1000.0,
    'Mars fuel depot multiplier per outbound Starship': 5.0,
    'Mars payload per surface-landed Starship (kg)': 100000.0,
    'Max Starship build-capacity added per year (ships/yr)': 15.0,
    'Minimum cash buffer ($mm)': 0.0,
    'Module operating cost: Lunar (% of Lunar CapEx)': 0.05,
    'Module operating cost: Mars (% of Mars CapEx)': 0.05,
    'ODC R&D — CAGR (taper)': -0.15,
    'ODC R&D — end-state % (floor)': 0.08,
    'ODC R&D — start % of ODC rev': 0.3,
    'ODC fleet design life (years)': 5.0,
    'ODC ground ops % of revenue': 0.05,
    'ODC insurance % of revenue': 0.01,
    'ODC insurance pct rev': 0.01,
    'ODC other COGS % of revenue': 0.03,
    'ODC other COGS pct rev': 0.03,
    'ODC strategic seed graduation IRR': -1.0,
    'ODC strategic seed ramp (years)': 5.0,
    'ODC utilization factor': 0.85,
    'Orbital PUE uplift vs terrestrial': 0.8000000000000002,
    'Other corporate operating: flat % of group rev': 0.01,
    'Payload: booster-only mode (kg-to-LEO)': 0.0,
    'Payload: fully reusable mode (kg-to-LEO)': 100000.0,
    'Pre-IPO bridge year of drawdown': 2026.0,
    'Pre-IPO debt facility ($mm)': 20000.0,
    'Raptor engines per booster (Super Heavy)': 33.0,
    'Raptor engines per ship (2nd stage)': 3.0,
    'Sales & Marketing — start % of (Starlink+Starshield+Customer Launch ext) rev': 0.04,
    'Sales & Marketing: CAGR (taper)': -0.08,
    'Sales & Marketing: end-state % (floor)': 0.02,
    'Sat facility capacity-ratio CapEx exponent': 1.0,
    'Sat factory base capacity 2025 (sats/yr)': 0.0,
    'Sat factory capacity (sats/yr per increment)': 1.0,
    'Sat factory cost per capacity increment ($mm)': 0.0,
    'Sat factory useful life (years)': 20.0,
    'Satellite Dep per kg — annual decay rate': 0.01,
    'Satellite Dep per kg: base year ($/kg/yr)': 128.8,
    'Satellite cost per kg: base year ($/kg)': 650.0,
    'Satellite cost per kg: learning rate': 0.0,
    'Satellite useful life — V2 Mini (years)': 5.0,
    'Satellite useful life — V2 Mini DTC (years)': 3.0,
    'Satellite useful life — V3 (years)': 5.0,
    'Satellite useful life — V3 DTC (years)': 3.0,
    'Sats per F9 launch — V2 BB': 29.0,
    'Sats per F9 launch — V2 DTC': 7.0,
    'Sats per Starship launch — V3 BB': 60.0,
    'Sats per Starship launch — V3 DTC': 15.0,
    'Spectrum useful life (years)': 15.0,
    'Starlink R&D: CAGR (taper)': -0.1,
    'Starlink R&D: end-state % (floor)': 0.03,
    'Starlink R&D: start % of (Starlink+Starshield) rev': 0.08,
    'Starlink ground ops % of revenue': 0.04,
    'Starlink insurance % of revenue': 0.01,
    'Starlink other COGS % of revenue': 0.02,
    'Starshield Reserved % — decay rate': 0.25,
    'Starshield Reserved % — floor': 0.0001,
    'Starshield Reserved % — start': 0.0257,
    'Starshield Rev per Gbps — base year ($/Gbps)': 164699.0,
    'Starshield Rev per Gbps — decay rate': 0.05,
    'Starshield S-1 Government Connectivity scope factor': 1.0,
    'Starship 2nd-stage manufacturing cost ($mm/unit, base)': 36.0,
    'Starship booster share of manufacturing cost (% of stack mfg)': 0.6,
    'Starship build-capacity ceiling (ships/yr)': 250.0,
    'Starship cost WL anchor cum units (= cum stacks at end-2024 baseline)': 4.0,
    'Starship facility capacity (ships/yr per Gigabay)': 100.0,
    'Starship facility cost per Gigabay increment ($mm)': 500.0,
    'Starship facility useful life (years)': 30.0,
    'Starship launches per pad per year': 50.0,
    'Starship manufacturing WL learning rate (% reduction per doubling cum stacks)': 0.15,
    'Starship manufacturing cost anchor ($mm/stack, 2024 baseline)': 90.0,
    'Starship operational year': 2025.0,
    'Starship ops + fuel cost anchor ($mm/launch, 2024 baseline)': 12.0,
    'Starship ops/refurb WL learning rate (% reduction per doubling cum stacks)': 0.1,
    'Starship payload — 2025 baseline (kg-to-LEO, fully reusable mode)': 100000.0,
    'Starting BoY 2025 subscribers (millions)': 5.0,
    'Subsidy mix (% of net adds subsidized)': 0.5,
    'Subsystem cost pre-WL ($/sat)': 0.0,
    'Super Heavy manufacturing cost ($mm/unit, base year)': 54.0,
    'TAM inflation rate (annual)': 0.025,
    'Terafab capacity per fab phase (wspm/phase)': 1.0,
    'Terafab fab CapEx (blended all-in $/wspm)': 0.0,
    'Terafab fab construction window (years)': 3.0,
    'Terafab fab useful life (depreciation, years)': 20.0,
    'Terafab facility cap ($mm)': 0.0,
    'Terafab facility draw-window end year': 2030.0,
    'Terafab facility interest rate (annual)': 0.0,
    'Terafab facility repaid-by year': 2035.0,
    'Terafab good chips per wspm per yr': 1.0,
    'Terafab production cost frac (chip at-cost, → DC CapEx)': 0.33,
    'Terafab: SpaceX cost/capacity share (frac)': 1.0,
    'Terminal COGS per unit ($)': 500.0,
    'Terminal factory CapEx toggle (1=on,0=off)': 0.0,
    'Terminal factory capacity (kits/yr per increment)': 1.0,
    'Terminal factory cost per capacity increment ($mm)': 0.0,
    'Terminal factory useful life (years)': 20.0,
    'Terminal growth rate g (group + most modules)': 0.025,
    'Terminal replacement rate (% installed/yr)': 0.05,
    'Terminal retail price ($, non-subsidized)': 500.0,
    'Terminal retail price ($, subsidized)': 300.0,
    'Terrestrial $/MW build': 20000000.0,
    'Terrestrial facility cost CAGR': 0.047,
    'Total customer launch market CAGR (% growth/yr)': 0.0,
    'V2 BB sat mass (kg)': 575.0,
    'V2 Mini BB Active Sats — end-2025': 5246.0,
    'V2 Mini BB Sats Launched 2025': 2987.0,
    'V2 Mini BB historical baseline (SoY 2025)': 5246.0,
    'V2 Mini Bandwidth per Sat — BB (Gbps)': 96.0,
    'V2 Mini Bandwidth per Sat — DTC (Gbps)': 0.2,
    'V2 Mini DTC Active Sats — end-2025': 650.0,
    'V2 Mini DTC Sats Launched 2025': 182.0,
    'V2 Mini DTC historical baseline (SoY 2025)': 650.0,
    'V2 Mini Mass (kg)': 575.0,
    'V2 Mini cost per kg — base year ($/kg)': 650.0,
    'V2 phase-out year (no V2 BB / V2 DTC launches from this year)': 2028.0,
    'V3 BB Bandwidth per Sat — base year (Gbps)': 1000.0,
    'V3 BB Sats Launched 2025': 0.0,
    'V3 BB first launch year': 2026.0,
    'V3 BB sat mass (kg)': 2000.0,
    'V3 BB sat unit cost ($mm/sat)': 50.0,
    'V3 DTC Bandwidth per Sat (Gbps)': 2.75,
    'V3 DTC Sats Launched 2025': 0.0,
    'V3 DTC first launch year': 2028.0,
    'V3 Mass (kg)': 2000.0,
    'V3 Starlink launch trigger year': 2027.0,
    'Vehicle build lead time (years)': 2.0,
    'WL learning rate: turnaround vs cum upmass doubling': 0.15,
    'Workload mix — inference share': 0.85,
    "Wright's Law floor pct (of base subsystem cost)": 0.2,
}
